### 게시글 생성
POST /localhost:8080/posts
Content-Type: application/json

{
    "title":"title",
    "content":"content",
    "createdBy":"createdBy",
    "tags": ["tag1", "tag2", "tag3"]
}

### 게시글 수정
PUT /localhost:8080/posts/20
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "updatedBy": "createdBy",
    "tags": ["tag1", "tag2", "tag3"]
}


### 게시글 삭제
DELETE /localhost:8080/posts/1?createdBy=yeonuel

### 게시글 상세 조회
GET /localhost:8080/posts/23

### 게시글 목록 조회
GET /localhost:8080/posts
